### ISSUE TITLE
Improve `while` lifting

### ISSUE THREAD

**Issue by frabert** [lifting-bits/rellic#185]
Currently, a loop such as this

    while(cond) {
        body
    }
    rest

is lifted like this:

    while(cond) {
      body
    }
    if(!cond) {
      rest
    }

It would be nice to get rid of the redundant `if`

**Comment by frabert** [comment]
Can you elaborate on why rewriting rules would not be a good approach?

**Comment by surovic** [comment]
> For example, maybe what you're saying is that there is a place in rellic where we have the context to ask z3 about cond and !cond, whereas in an ast rewrite rule, it requires a structural pattern match, so it would seem to be more natural to do it where the z3 context is.

This is exactly the reason. Pattern matching is fragile in the sense that for each pattern, there can be slews of corner cases that will either require bigger or more patterns. If not kept in check this can become unmaintainable pretty fast. And since the core issue is going to be finding the `!cond` guarded `if` to a `while(cond)`, Z3 is the way to go. In fact, a very similar structurization pass already exists in `CondBasedRefine.(h|cpp)`.

However I think this is not entirely the same issue. If we remove the `if (!cond)` guard entirely, we need to place `rest` in the right place, otherwise execution order might not be preserved. Consider the following case:

```C
while (cond_a) {
    // body
}

if (cond_b) {
    // body
}

if (!cond_a) {
    // rest
}
```
In this case one needs to investigate the logical relationship between `cond_a` and `cond_b` to be safe. Note that this is an example I came up with on the fly. I don't know if this is a common occurrence or not. But for the sake of robustness and generality we should think through how we approach this problem. Or better yet, if there is a solution available in the mentioned papers, we should use it.

> If that's the case, do we have a notion of z3-available rewrite patterns/rules/frameworks -- something that straddles the two domains?

No, we currently do not. However, in "Helping Johnny Analyze Malware", there's section 4 and section 5 that deal with logic-based rewriting and control-flow (mainly loop) transformations respectively.
