### ISSUE TITLE
Implement VisitFunctionDecl for simplifying expressions with function calls

### ISSUE THREAD

**Issue by meme** [lifting-bits/rellic#46]
During simplification of expressions with function calls in the expression, the Z3 conversion visitor will fail to convert function calls properly as per: https://github.com/lifting-bits/rellic/blob/master/rellic/AST/Z3ConvVisitor.cpp#L327

I am not entirely sure as to how this should be implemented, I was thinking something along the lines of emitting an opaque Z3 interpreted function through (how do I get the parameters in there?) and then "interpreting" it as a function call right through. Does this sound like the optimal way? Open to suggestions, would be willing to implement.

**Comment by surovic** [comment]
> I am not entirely sure as to how this should be implemented, I was thinking something along the lines of emitting an opaque Z3 interpreted function through (how do I get the parameters in there?) and then "interpreting" it as a function call right through.

I'm not sure if I understand what you mean by "interpretation" and "interpreted function" here. I might be wrong, but as far as I know, Z3 function interpretations are other Z3 expressions. So the above would mean having to translate whole function bodies from C to Z3, in case we have the function body available. If the function body is not available, we'd have to emulate it? Either way I think that's far beyond the scope of what is feasible for the time being.

I'd suggest maybe using an opaque Z3 **uninterpreted** function? But even then this is a pretty tricky issue, because a lot of C functions have side-effects and the result of the function call may be dependent on when the function is called. Therefore function call can't generally be moved around without changing the semantics of the code.

Overall this is something I'd have to do some research on before implementing a proper conversion visitor. Maybe for the time being we could just ignore expressions with function calls during Z3 based simplification passes.

**Comment by meme** [comment]
I agree it is best to just ignore expressions with function calls for now, how should I go about this?

**Comment by surovic** [comment]
Looking at it, even ignoring the conditions won't be trivial either, since some AST passes use the Z3 expressions in non-trivial ways. Once I take a good look at this, I'll get back to you with ideas.

**Comment by surovic** [comment]
Quick and dirty idea: create a helper variable right before the condition. Something along the lines of
```C
int f(int a, int b) {
    return a == b;
}

int main(void) {
    if (f(0, 1)) {
        return 0;
    } else {
        return 1;
    }
}
```
would change to

```C
int f(int a, int b) {
    return a == b;
}

int main(void) {
    int hlp = f(0, 1);
    if (hlp) {
        return 0;
    } else {
        return 1;
    }
}
```
I think this would make all the affected AST passes ignore the condition. The transformation could be implemented similarly to rewriting rules in [rellic/AST/ExprCombine.cpp](https://github.com/lifting-bits/rellic/blob/master/rellic/AST/ExprCombine.cpp)
