### ISSUE TITLE
if build.sh is run twice, it errors out

### ISSUE THREAD

**Issue by rofl0r** [lifting-bits/rellic#89]
first it failed because ninja wasn't installed, so i called the build.sh again, resulting in:

```
CMake Error at cmake/vcpkg_helper.cmake:17 (message):
  Please define a path to VCPKG_ROOT.  See
  https://github.com/trailofbits/cxx-common for more details.  Or if you
  don't want to use vcpkg dependencies, add '-DUSE_SYSTEM_DEPENDENCIES=ON'
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)
```

i then rm -rf'd the rellic-build dir, downloaded the 500 MB of stuff again, just to get
```
  Could NOT find Git (missing: GIT_EXECUTABLE)
```
(i assumed if i cloned the repo before entering the ubuntu rootfs i wouldnt need it)

running build.sh again results in the same error as above.
i guess i have to wait another hour to download the 500MB again and see what comes before the next error.

**Comment by ekilmer** [comment]
@rofl0r Sorry to hear that you're encountering issues with the build script. We are actively trying to improve that aspect of the lifting tools.

Could you check out the script in PR #91 and let me know if that solves any of your issues?

As for requiring git, it is used to determine version information. We should probably have a way to continue silently, since git isn't a required dependency for any interesting features.
